### ISSUE TITLE
issue when changing from arabic to another language

### ISSUE THREAD

**Issue by mohammadameer** [Avansai/next-multilingual#42] opened 2023-08-10 18:59 UTC
thanks for the great package,

my app uses 2 languages arabic and english, i'm following the docs and the example, when i change from english to arabic it work without issues,the languange and the slug change, but when changing from arabic to english only the language change and slug keep the same and i get 404 error, 

it took me hours trying different things, i added fr-CA and its work without issues changes with english 

but i get the issue when changing from arabic to any other language

![CleanShot 2023-08-10 at 21 57 57](https://github.com/Avansai/next-multilingual/assets/35637666/473f31bd-0747-40e6-8c35-31a6a70da3fa)

**Comment by nbouvrette** [comment] 2023-08-10 20:05
@mohammadameer which version of Next.js are you using? I am about to release a fix to support the latest version... they release some breaking changes in version `13.4.13`

**Comment by mohammadameer** [comment] 2023-08-11 04:06
my pacakges versions
```
"next": "^13.4.12",
"next-multilingual": "^5.0.14",
```

**Comment by mohammadameer** [comment] 2023-08-11 04:14
the issue is not related to arabic, it happen wehn changing from the default langauge to any other language

changed the default to en-US and now when changing to any other route, only the language change without the path

**Comment by nbouvrette** [comment] 2023-08-11 04:27
Sorry that you spent so much time troubleshooting this.

It would help of you could share a repository reproducing the issue.

Otherwise my hypothesis is that yout default language is not English. Since Next.js relies on the file path (using English characters), this package was build and tested on that foundation. For this package to work correctly, your file path under the pages directory should match the English slugs.

I think in theory it would be possible to support non English default languages but since we never needed this capability, and no one asked for it so far, it was never investigated further.

If you can share some code it would help me confirm my hypothesis.

**Comment by mohammadameer** [comment] 2023-08-11 05:16
No worries, i've mad this simple example where i'm facing the issue

https://github.com/mohammadameer/next-multilingual

and reading your comment again, yes you are right that was the issue, using non english as the default language and also non matching english slug with folder naming

would be great if these info are added to the project readme

**Comment by nbouvrette** [comment] 2023-08-11 13:32
You're right I will add a mention.. since honestly this has never been tested or requested because - I can definitely add a warning.

Are you able to unblock yourself and use the package given these limitations? I've honestly always wanted to check how much effort it would be to support this but given that I personally don't need this and the demand doesn't seem there for now, I'm not sure how much time I can personally spend on this right now.

Also if you are interesting into contributing, I'm always happy to get extra help to improve the package.

On another notes I took a quick look at your repository and noticed that you are missing this config in the Next.js config:

```
experimental: {
    esmExternals: false,
  }
```

Also If I check this page: https://github.com/mohammadameer/next-multilingual/blob/main/pages/details/index.en-US.properties

Your English slug should match the file system, so for that page you should use `details` or, if you want to use `details page` as slug, you should rename the directory to `details-pages`.

This is the part that has never really been tested - your file system should match your English slugs - or in fact it doesn't have to be English, it can be any language that will be able to use the file system character sets.. which I think are mostly limited to ASCII characters.

**Comment by nbouvrette** [comment] 2023-08-11 13:43
FYI I added a clarification in the readme - hopefully this will help

https://github.com/Avansai/next-multilingual/commit/d6c8338986b1fa0f0d592de595a96d1d74f36187

**Comment by mohammadameer** [comment] 2023-08-13 06:58
@nbouvrette thank you very much, currently i'm going with making english the default language

i think that should not be an issue with users who came from google search, as google will show correct result that match their intent, correct language and slug

but for users who use the url directly will it detect the language or show the default language

will be very happy to contribute, will need to understand how the package is working

**Comment by nbouvrette** [comment] 2023-08-13 23:07
Keep in mind that the default language only applies if you set an homepage that use dynamic locale resolution like our example. The default would only be picked for someone who didn't have Arabic in their OS/Browser preference. You could always override it if you want... the only real requirement really is that you have an English locale on the site to mimic the file system slugs.

I'm going to close this issue for now and please message me on Twitter @nicolasbou if you are serious about contributing and I am even ready to jump on a call with you to help you get started.

**Closed by nbouvrette** 2023-08-13 23:07 UTC
Labels: bug
