### ISSUE TITLE
locale should also be lowercase

### ISSUE THREAD

**Issue by TomFreudenberg** [Avansai/next-multilingual#30] opened 2022-02-17 23:34 UTC
When using `useMessages()` and router.locale = 'en-US' the messages gets not found.

https://github.com/Avansai/next-multilingual/blob/main/src/messages/index.tsx#L217

![grafik](https://user-images.githubusercontent.com/410087/154588985-2775e0af-ca92-4ffe-af19-79dce9d6e3cf.png)

should be:

```js
return handleMessages(this, 'useMessages', locale.toLowerCase());
```

As is already done on `getMessages()`

https://github.com/Avansai/next-multilingual/blob/main/src/messages/index.tsx#L228

![grafik](https://user-images.githubusercontent.com/410087/154589203-01fc50a7-d4df-402f-8b42-9eff9fcb8d7a.png)

**Comment by TomFreudenberg** [comment] 2022-02-17 23:34
Ping @nbouvrette

**Comment by nbouvrette** [comment] 2022-02-18 00:00
How is your locale `en-US` on the route? when you use the config examples in the readme it should lowercase the locale to keep URLs lowercased.

**Comment by TomFreudenberg** [comment] 2022-02-18 00:03
This is happen running outside of nextJS when building tests (jest) and storybook. 

Off-topic:

By the way storybook may also work. I come up with an description for that.

**Comment by nbouvrette** [comment] 2022-02-18 00:12
Ok I guess you will have to lowercase your locale in Jest since its the expected behavior when using our Config APIs.

Good to hear about Storybook.

Feel free to open a [discussion](https://github.com/Avansai/next-multilingual/discussions) if you want to share your findings.

Closing this issue for now.

**Closed by nbouvrette** 2022-02-18 00:12 UTC

**Comment by nbouvrette** [comment] 2022-02-18 15:59
Not really, because you specify directly the locale as a parameter in `getMessages()` which I think is preferable to use the BCP47 capitalization convention. 

But since Next.js uses router locales in a case-sensitive manner, we to the `toLowerCase()` in the configuration instead of every time calling `useMessages()`.

Remember that `next-multilingual` has been built (and optimized) for Next.js.

I don't think it would be a good pattern to start adding `toLowerCase()` to every function which has a locale parameter either. In fact, we try to normalize it whenever it makes sense (e.g., in the `<Head>`).

I've considered splitting the BabelPlugin and message functionalities into a more generic package but it hasn't been a priority so far for us to do this.

**Comment by TomFreudenberg** [comment] 2022-02-19 11:57
> I don't think it would be a good pattern to start adding `toLowerCase()` to every function which has a locale parameter either.

Maybe you are right with that - I have to think about ;-)
